# Generated by Django 5.0.3 on 2024-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_type",
            field=models.CharField(
                choices=[("Opinion", "Opinion"), ("Analysis", "Analysis")],
                max_length=256,
            ),
        ),
    ]
