# Generated by Django 5.0.6 on 2024-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_article_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="article",
            name="secondary_heading",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snippet",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
