# Generated by Django 5.0.6 on 2024-07-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_article_is_active_article_secondary_heading_and_more"),
        ("category", "0003_carousalitem_article_id_carousalitem_snippet_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="category.category",
            ),
        ),
    ]
