# Generated by Django 5.0.6 on 2024-07-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_snippet_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_type",
            field=models.CharField(max_length=256),
        ),
    ]
