# Generated by Django 5.0.3 on 2024-06-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_alter_article_article_type"),
        ("category", "0002_carousalitem_category_delete_cateogry"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousalitem",
            name="article_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="carousalitem",
            name="snippet_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="article.snippet",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="back_ground_image",
            field=models.FileField(
                blank=True, null=True, upload_to="category/back_ground_image/"
            ),
        ),
    ]
