# Generated by Django 5.0.3 on 2024-04-25 11:53

import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_country_alter_profile_email_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="prefrences",
        ),
        migrations.AddField(
            model_name="profile",
            name="country_of_residence",
            field=django_countries.fields.CountryField(
                blank=True, default="CA", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, default="CA", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default=None, max_length=128, region=None
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProfileSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("link", models.URLField(max_length=500)),
                ("social_platform", models.CharField(max_length=50)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_platform_links",
                        to="user.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
