# Generated by Django 5.0.6 on 2024-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_profile_country_remove_profile_prefrences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_residence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
