# Generated by Django 5.0.6 on 2024-06-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_country_of_residence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is staff"),
        ),
    ]
